### ISSUE TITLE
Cannot create ALIAS target PNG::PNG

### ISSUE THREAD

**Issue by tjom** [hunter-packages/libpng#6]
Hi, there seems to be an issue with the latest commit [5e3f12a](https://github.com/hunter-packages/libpng/commit/5e3f12aaba75f5865516eecd62f84ef3d305254e) for older versions of cmake.

`CMake Error at [...]/.hunter/_Base/[...]/Install/lib/cmake/PNG/PNGConfig.cmake:13 (add_library):
  add_library cannot create ALIAS target "PNG::PNG" because target "PNG::png"
  is IMPORTED.`

I think this requires cmake 3.11 or later.

**Comment by ruslo** [comment]
> I think this requires cmake 3.11 or later.

Yes: https://github.com/hunter-packages/libpng/commit/b489d853690dc99caa05021d0ea4ddbecc76913a

**Comment by tjom** [comment]
> > I think this requires cmake 3.11 or later.
> 
> Yes: [b489d85](https://github.com/hunter-packages/libpng/commit/b489d853690dc99caa05021d0ea4ddbecc76913a)

Would you see an issue with using an interface library instead of the alias in order to support older versions of cmake? I was thinking of something like:

```
add_library(PNG::PNG INTERFACE IMPORTED)
set_target_properties(PNG::PNG PROPERTIES
  INTERFACE_LINK_LIBRARIES "PNG::png"
)
```

**Comment by ruslo** [comment]
> Would you see an issue with using an interface library instead of the alias in order to support older versions of cmake?

It would be easier to add `if(CMAKE_VERSION ...)` check.

**Comment by tjom** [comment]
> It would be easier to add `if(CMAKE_VERSION ...)` check.

Sure, I just thought the alias target was needed by some other library which would then fail to build? Or is it merely to allow different naming conventions?

**Comment by ruslo** [comment]
> I just thought the alias target was needed by some other library which would then fail to build?

Yes: https://github.com/ruslo/hunter/issues/1858

I think adding interface target will make the adaptation harder:
- https://github.com/qt/qtbase/commit/fae5691c7f78f8a0154c9cea28b6639327a90550

Logically it's an alias and not a new target. Also if this change will be applied the documentation should be updated too:
- https://docs.hunter.sh/en/latest/packages/pkg/PNG.html

**Comment by tjom** [comment]
> Also if this change will be applied the documentation should be updated too:
> 
> * https://docs.hunter.sh/en/latest/packages/pkg/PNG.html

I opened pull requests for branches [1.6.26](https://github.com/hunter-packages/libpng/pull/7) and [1.6.36](https://github.com/hunter-packages/libpng/pull/8) and updated the documentation in [hunter](https://github.com/ruslo/hunter/pull/1918).

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
